/*
Copyright  © Trustonic Limited 2013

All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

  1. Redistributions of source code must retain the above copyright notice, this
     list of conditions and the following disclaimer.

  2. Redistributions in binary form must reproduce the above copyright notice,
     this list of conditions and the following disclaimer in the documentation
     and/or other materials provided with the distribution.

  3. Neither the name of the Trustonic Limited nor the names of its contributors
     may be used to endorse or promote products derived from this software
     without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
OF THE POSSIBILITY OF SUCH DAMAGE.
*/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gd_mobicore_pa_jni_CommonPAWrapper */

#ifndef _Included_com_gd_mobicore_pa_jni_CommonPAWrapper
#define _Included_com_gd_mobicore_pa_jni_CommonPAWrapper
#ifdef __cplusplus
extern "C" {
#endif
#undef com_gd_mobicore_pa_jni_CommonPAWrapper_IMEI_ESN_INDEX
#define com_gd_mobicore_pa_jni_CommonPAWrapper_IMEI_ESN_INDEX 0L
#undef com_gd_mobicore_pa_jni_CommonPAWrapper_MNO_INDEX
#define com_gd_mobicore_pa_jni_CommonPAWrapper_MNO_INDEX 1L
#undef com_gd_mobicore_pa_jni_CommonPAWrapper_BRAND_INDEX
#define com_gd_mobicore_pa_jni_CommonPAWrapper_BRAND_INDEX 2L
#undef com_gd_mobicore_pa_jni_CommonPAWrapper_MANUFACTURER_INDEX
#define com_gd_mobicore_pa_jni_CommonPAWrapper_MANUFACTURER_INDEX 3L
#undef com_gd_mobicore_pa_jni_CommonPAWrapper_HARDWARE_INDEX
#define com_gd_mobicore_pa_jni_CommonPAWrapper_HARDWARE_INDEX 4L
#undef com_gd_mobicore_pa_jni_CommonPAWrapper_MODEL_INDEX
#define com_gd_mobicore_pa_jni_CommonPAWrapper_MODEL_INDEX 5L
#undef com_gd_mobicore_pa_jni_CommonPAWrapper_VERSION_INDEX
#define com_gd_mobicore_pa_jni_CommonPAWrapper_VERSION_INDEX 6L
#undef com_gd_mobicore_pa_jni_CommonPAWrapper_RESPONSE_ARRAY_SIZE
#define com_gd_mobicore_pa_jni_CommonPAWrapper_RESPONSE_ARRAY_SIZE 7L
/*
 * Class:     com_gd_mobicore_pa_jni_CommonPAWrapper
 * Method:    openSession
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_gd_mobicore_pa_jni_CommonPAWrapper_openSession
  (JNIEnv *, jobject);

/*
 * Class:     com_gd_mobicore_pa_jni_CommonPAWrapper
 * Method:    closeSession
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gd_mobicore_pa_jni_CommonPAWrapper_closeSession
  (JNIEnv *, jobject);

/*
 * Class:     com_gd_mobicore_pa_jni_CommonPAWrapper
 * Method:    executeCmpCommands
 * Signature: (ILjava/util/List;Ljava/util/List;)I
 */
JNIEXPORT jint JNICALL Java_com_gd_mobicore_pa_jni_CommonPAWrapper_executeCmpCommands
  (JNIEnv *, jobject, jint, jobject, jobject);

/*
 * Class:     com_gd_mobicore_pa_jni_CommonPAWrapper
 * Method:    getVersion
 * Signature: ([BLjava/util/List;Ljava/util/List;)I
 */
JNIEXPORT jint JNICALL Java_com_gd_mobicore_pa_jni_CommonPAWrapper_getVersion
  (JNIEnv *, jobject, jbyteArray, jobject, jobject);

/*
 * Class:     com_gd_mobicore_pa_jni_CommonPAWrapper
 * Method:    getSuid
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_gd_mobicore_pa_jni_CommonPAWrapper_getSuid
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_gd_mobicore_pa_jni_CommonPAWrapper
 * Method:    isRootContainerRegistered
 * Signature: ([Z)I
 */
JNIEXPORT jint JNICALL Java_com_gd_mobicore_pa_jni_CommonPAWrapper_isRootContainerRegistered
  (JNIEnv *, jobject, jbooleanArray);

/*
 * Class:     com_gd_mobicore_pa_jni_CommonPAWrapper
 * Method:    isSpContainerRegistered
 * Signature: (I[Z)I
 */
JNIEXPORT jint JNICALL Java_com_gd_mobicore_pa_jni_CommonPAWrapper_isSpContainerRegistered
  (JNIEnv *, jobject, jint, jbooleanArray);

/*
 * Class:     com_gd_mobicore_pa_jni_CommonPAWrapper
 * Method:    getSPContainerState
 * Signature: (I[I)I
 */
JNIEXPORT jint JNICALL Java_com_gd_mobicore_pa_jni_CommonPAWrapper_getSPContainerState
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     com_gd_mobicore_pa_jni_CommonPAWrapper
 * Method:    getSPContainerStructure
 * Signature: (I[I[[B[I)I
 */
JNIEXPORT jint JNICALL Java_com_gd_mobicore_pa_jni_CommonPAWrapper_getSPContainerStructure
  (JNIEnv *, jobject, jint, jintArray, jobjectArray, jintArray);

/*
 * Class:     com_gd_mobicore_pa_jni_CommonPAWrapper
 * Method:    doProvisioning
 * Signature: (II[B)I
 */
JNIEXPORT jint JNICALL Java_com_gd_mobicore_pa_jni_CommonPAWrapper_doProvisioning
  (JNIEnv *, jobject, jint, jint, jbyteArray);

/*
 * Class:     com_gd_mobicore_pa_jni_CommonPAWrapper
 * Method:    installTrustlet
 * Signature: (I[B[B)I
 */
JNIEXPORT jint JNICALL Java_com_gd_mobicore_pa_jni_CommonPAWrapper_installTrustlet
  (JNIEnv *, jobject, jint, jbyteArray, jint, jbyteArray, jbyteArray);

/*
 * Class:     com_gd_mobicore_pa_jni_CommonPAWrapper
 * Method:    unregisterRootContainer
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_gd_mobicore_pa_jni_CommonPAWrapper_unregisterRootContainer
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_gd_mobicore_pa_jni_CommonPAWrapper
 * Method:    setEnvironmentVariable
 * Signature: ([B[B)I
 */
JNIEXPORT void JNICALL Java_com_gd_mobicore_pa_jni_CommonPAWrapper_setEnvironmentVariable
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
